#!/usr/bin/env php
<?php
/**
 * Recursively copy files from one directory to another
 *
 * @param string $src - Source of files being moved
 * @param string $dst - Destination of files being moved
 *
 * @return bool
 */
function rcopy($src, $dst)
{
    // If source is not a directory stop processing
    if (!is_dir($src)) {
        return false;
    }

    // If the destination directory does not exist create it
    if (!is_dir($dst)) {
        if (!mkdir($dst)) {
            // If the destination directory could not be created stop processing
            return false;
        }
    }

    // Open the source directory to read in files
    $i = new DirectoryIterator($src);
    foreach ($i as $f) {
        if ($f->isFile()) {
            copy($f->getRealPath(), "$dst/" . $f->getFilename());
        } else if (!$f->isDot() && $f->isDir()) {
            rcopy($f->getRealPath(), "$dst/$f");
        }
    }

    return true;
}

$source = 'vendor/';
$destination = 'database/migrations/';

$vendors = new DirectoryIterator($source);
foreach ($vendors as $vendor) {
    if (!$vendor->isDot() && $vendor->isDir()) {
        $products = new DirectoryIterator($source . $vendor);
        foreach ($products as $product) {
            if (!$product->isDot() && $product->isDir()) {
                $potential = $product->getRealPath() . '/database/migrations/';
                if (is_dir($potential)) {
                    rcopy($potential, $destination);
                }
            }
        }
    }
}
